core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/',views.index,name="index"),
   
   
]

socol/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authy.urls')),
    path('',include('core.urls')),
    path('',include('user.urls')),
    # path('core/',include('core.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import CustomUserManager
from django.contrib.auth.models import User
from crum import get_current_user


Gender_choices = [('M','Male'),('F','Female'),('None','Prefer not to say')]

class Profile(models.Model):   #we create the model but inherited AbstractUser ,AbstractUser is the User model but not completed means the data include but not save and create the main User Module

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    full_name = models.CharField(max_length=100, help_text='Help people discover your account by using the name you\'re known by: either your full name, nickname, or business name.')
    # email = models.EmailField(unique=True)

    #Optional Field
    bio = models.TextField(null = True,blank=True, help_text='Provide your personal information, even if the account is used for a business, a pet or something else. This won\'t be a part of your public profile.')
    website = models.URLField(null = True,blank=True)
    phone_number = models.CharField(max_length=20,null=True,blank=True)
    gender = models.CharField(max_length=10,choices=Gender_choices,null=True,blank=True)
    is_private_account = models.BooleanField(null=True,blank=True)

    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS= ['full_name','username',] 

    # first_name = None
    # last_name = None

    # objects = CustomUserManager() # we are using our Customizing model

    def __str__(self):
        return self.user.email
    
    def save(self,*args,**kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:     #pk will get at the time the model was built means the data save then get the primary key
            self.user = user
        super(Profile,self).save(*args,**kwargs)

    
    def username(self):
        return self.user.username
    
    def email(self):
        return self.user.email
 
    @property
    def follower_count(self):
        count = self.follow_followed.count()    #it counts the current instance user has how much followings 
        return count
    
    @property
    def following_count(self):
        count= self.follow_follower.count()
        return count
    
    

authy/forms.py
from django import forms
from django.contrib.auth.models  import User
# from user.models  import Profile
from django.contrib.auth.forms import UserCreationForm

class UserRegistration(UserCreationForm):
    first_name = forms.CharField(label='First Name',widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(label='last Name',widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.CharField(required=True ,widget=forms.EmailInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = [ 'username','email','first_name','last_name','password1','password2']

templates/authentication/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra_head %}{% endblock %}
    {% comment %} <link rel="stylesheet" href="{% static "css/index.css" %}" /> {% endcomment %}

    <title>Socol</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

  </body>
</html>

templates/authentication/password_change.html
{% extends 'core/base1.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 7rem;">
        <div class="row">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="card-header">
                        <p class="m-0" style="color: #5f5f5f;">Change Password</p>
                    </div>
                    <div class="card-body offset-md-2">
                        <form method="POST">
                            {% csrf_token %}

                            <!-- Password Change Form -->
                            {% for field in form %}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label col-form-label-sm text-md-right font-weight-bolder" for="{{ field.auto_id }}">
                                        {{ field.label }}
                                    </label>
                                    <div class="col-sm-8">
                                        {{ field }}
                                        <small id="passwordHelpBlock" class="form-text text-muted">
                                            {{ field.help_text }}
                                        </small>
                                        <div class="{% if field.errors %}validation__error{% else %}invalid-feedback{% endif %}">
                                            {{ field.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- End Password Change Form -->

                            <div class="offset-md-2 my-1">
                                <button class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authentication/password_change_done.html
{% extends 'core/base1.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 7rem;">
        <div class="row ">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="text-center p-5">

                        <!-- Password Changed Success Message -->
                        <p class="text-muted">Congratulations, your password has been successfully changed. 
                            <a href="{% url 'profile_view' request.user.username %}">Go Back to Profile</a>
                        </p>
                        <!-- End Password Changed Success Message -->

                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authentication/password_reset.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" required maxlength="240" autocomplete="email">
                            </div>
                            {% comment %} {{form.as_p}} {% endcomment %}
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn">Send Signin Link</button>
                            </div>
                        </form>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_complete.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Successfully Reset</h4></div>
                    <div class="forgot__password__text py-2">
                        You can go ahead and signin now.
                        <br>
                        <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">
                            Click here to Sign In.
                        </a>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        {% if form %}
                            <div>
                                {% if form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ form.non_field_errors }}
                                    </div>
                                {% endif%}
                            </div>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="Password">
                                    <p>{{ form.new_password1.errors }}</p>
                                </div>
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Retype Password">
                                    <p>{{ form.new_password2.errors }}</p>
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Set Password</button>
                                </div>
                            </form>
                        {% else %}
                            <div class="py-2">
                                <strong style="color: #ff6600;">Your password reset link is invalid or expired.</strong>
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_done.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-4 mb-5">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Email Sent.</h4></div>
                    <div class="forgot__password__text py-2">
                        Check your registered email for the Password Reset link.
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_email.html
Ujval is trying to steal your password- {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/authentication/signin.html
{% extends 'authentication/base.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/signin.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-6 d-none d-md-block">
            <img src="#" class="signin__phone float-right">
        </div>
        <div class="col-sm-6 my-auto">
            <div class="">
                <div class="text-center card px-5 mr-md-auto signin__card">
                    <img src="#" class="insta__logo mt-4 mb-3 mx-auto">
                    <div class="signin">
                        <div class="signin__form mb-3">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-danger" role='alert'>
                                    {{ message }}
                                </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input id="id_email_username" type="text" name="email_username" placeholder="Email or Username">
                                </div>
                                <div class="my-1 form__input">
                                    <input id="id_password" type="password" name="password" placeholder="Password">
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Sign in</button>
                                </div>
                            </form>
                        </div>
                        <div class="text-center my-4">
                            <p class="or__text">OR</p>
                        </div>
                        
                        <div class="mb-4">
                            <a class="forogt__password text-decoration-none" href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>
                    </div>
                </div>
                <div class="text-center card mt-2 px-5 mr-md-auto signin__card">
                    <p class="have__an__account py-3">Don't have an account? <a href="{% url 'signup' %}" class="text-decoration-none">Sign up</a></p>
                </div>
                <div class="text-center mt-2 px-5 mr-auto get__app">
                    <p class="">Get the app.</p>
                    <div class="row">
                        <div class="col-6">
                            <img src="#" class="app__download__img">
                        </div>
                        <div class="col-6">
                            <img src="#" class="app__download__img">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/signup.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see photos and videos from your friends.</p>
                    {% comment %} <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div> {% endcomment %}
                    {% comment %} <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div> {% endcomment %}
                    <div>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif%}
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                 {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="first_name" placeholder="First Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                   {{ form.first_name.errors }}
                                </div>
                            </div>
                            
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="last_name" placeholder="Last Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                   {{ form.last_name.errors }}
                                </div>
                            </div>
                            
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1s.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                   {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                  {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="{% url 'signin_view' %}" class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}